version: "3"
services:
  web:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    environment:
      MONGO_URL: mongodb://db_user:db_pass@db:27017/
      API_KEY: "SOME KEY WE KEEP SECRET"
    volumes:
      - ./time_vault:/code/time_vault
    ports:
      - "8000:8000"

  db:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: db_pass
    ports:
      - "27017:27017"

  db-interface:
    image: mongo-express
    restart: "no"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: db_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: db_pass
      ME_CONFIG_MONGODB_URL: mongodb://db_user:db_pass@db:27017/