version: "3"
services:
  time-vault-api:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    environment:
      MONGO_URL: mongodb://db_user:db_pass@time-vault-db:27017/
      API_KEY: "SOME KEY WE KEEP SECRET"
    volumes:
      - .:/code
    ports:
      - "8008:8080"
    networks:
      - clock-backend_default
      - default

  time-vault-db:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: db_pass
    ports:
      - "27017:27017"
    networks:
      - default

  time-vaultdb-interface:
    image: mongo-express
    restart: "no"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: db_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: db_pass
      ME_CONFIG_MONGODB_URL: mongodb://db_user:db_pass@time-vault-db:27017/
    networks:
      - default

networks:
  clock-backend_default:
    external: true